# Generated by Django 5.0 on 2023-12-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('security_breach', 'Security Breach'), ('data_loss', 'Data Loss'), ('malware_attack', 'Malware Attack')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(default='open', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
